# Generated by Django 6.0.4 on 2026-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentosbebidas',
            fields=[
                ('id_alimentosbebidas', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alimento o Bebida',
                'verbose_name_plural': 'Alimentos y Bebidas',
                'db_table': 'alimentosbebidas',
            },
        ),
    ]
