# Generated by Django 6.0.4 on 2026-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentosbebidas',
            options={'managed': False, 'verbose_name': 'Alimento o Bebida', 'verbose_name_plural': 'Alimentos y Bebidas'},
        ),
    ]
