# Generated by Django 6.0.4 on 2026-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_celular', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(db_column='apellido_Paterno', max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('contrase_a', models.CharField(db_column='contrase??a', max_length=255)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_tipo_de_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
    ]
