# Generated by Django 6.0.4 on 2026-04-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_tipo_de_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_usuario', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_celular', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(db_column='apellido_Paterno', max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('contrase_a', models.CharField(db_column='contraseña', max_length=255)),
                ('id_tipo_de_usuario', models.ForeignKey(blank=True, db_column='id_tipo_de_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.perfiles')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
