# Generated by Django 6.0.4 on 2026-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='perfiles',
            options={'managed': False, 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
