# Generated by Django 6.0.4 on 2026-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('porcentaje_a_reducir', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'promocion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restricciones',
            fields=[
                ('id_restriccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('consumo_minimo_para_aplicar', models.IntegerField()),
            ],
            options={
                'db_table': 'restricciones',
                'managed': False,
            },
        ),
    ]
