# Generated by Django 6.0.4 on 2026-04-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restricciones',
            fields=[
                ('id_restriccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('consumo_minimo_para_aplicar', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Restriccion',
                'verbose_name_plural': 'Restricciones',
                'db_table': 'restricciones',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('porcentaje_a_reducir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('id_restriccion', models.ForeignKey(blank=True, db_column='id_restriccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='promociones.restricciones')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promocion',
            },
        ),
    ]
