# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promociones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restricciones",
            name="visitas_minimas_para_aplicar",
            field=models.IntegerField(default=0),
        ),
    ]
