# Generated by Django 6.0.4 on 2026-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={'managed': False, 'verbose_name': 'Promocion', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterModelOptions(
            name='restricciones',
            options={'managed': False, 'verbose_name': 'Restriccion', 'verbose_name_plural': 'Restricciones'},
        ),
    ]
