# Generated by Django 6.0.4 on 2026-05-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
