# Generated by Django 6.0.4 on 2026-04-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('promociones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productopedido',
            fields=[
                ('id_productopedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_alimentosbebidas', models.ForeignKey(blank=True, db_column='id_alimentosbebidas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu.alimentosbebidas')),
            ],
            options={
                'verbose_name': 'Producto Pedido',
                'verbose_name_plural': 'Productos Pedidos',
                'db_table': 'productopedido',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('canjeado', models.IntegerField(blank=True, null=True)),
                ('codigounico', models.IntegerField(unique=True)),
                ('id_promocion', models.ForeignKey(blank=True, db_column='id_promocion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='promociones.promocion')),
                ('nombre_usuario', models.ForeignKey(blank=True, db_column='nombre_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Detalleticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_productopedido', models.ForeignKey(blank=True, db_column='id_productopedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.productopedido')),
                ('id_ticket', models.ForeignKey(blank=True, db_column='id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.ticket')),
            ],
            options={
                'verbose_name': 'Detalle Ticket',
                'verbose_name_plural': 'Detalles Tickets',
                'db_table': 'detalleticket',
            },
        ),
    ]
