# Generated by Django 6.0.4 on 2026-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'detalleticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productopedido',
            fields=[
                ('id_productopedido', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'productopedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('canjeado', models.IntegerField(blank=True, null=True)),
                ('codigounico', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
