# Generated by Django 6.0.4 on 2026-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleticket',
            options={'managed': False, 'verbose_name': 'Detalle Ticket', 'verbose_name_plural': 'Detalles Tickets'},
        ),
        migrations.AlterModelOptions(
            name='productopedido',
            options={'managed': False, 'verbose_name': 'Producto Pedido', 'verbose_name_plural': 'Productos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'managed': False, 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
