# Generated by Django 6.0.4 on 2026-05-13 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_ticket_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleticket',
            name='id_ticket',
            field=models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='canjeado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
